
import java.util.Scanner;
import noppapeli3.Noppa;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 20130289
 */
public class Noppapeli3 extends javax.swing.JFrame {

    /**
     * Creates new form Noppapeli3
     */
    public Noppapeli3() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jlblalku = new javax.swing.JLabel();
        jbtnpelaa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtarea = new javax.swing.JTextArea();
        jbtnuusi = new javax.swing.JButton();
        jtxtpelaaja = new javax.swing.JTextField();
        jlblpelaaja = new javax.swing.JLabel();
        jtxtkone = new javax.swing.JTextField();
        jchkjaa = new javax.swing.JCheckBox();
        jbtnnollaa = new javax.swing.JButton();
        jlblkone = new javax.swing.JLabel();
        jlblohje = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblalku.setText("Pelataan venttiä kahdella nopalla konetta vastaan.");

        jbtnpelaa.setText("Pelaa");
        jbtnpelaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpelaaActionPerformed(evt);
            }
        });

        jtxtarea.setColumns(20);
        jtxtarea.setRows(5);
        jScrollPane1.setViewportView(jtxtarea);

        jbtnuusi.setText("Uusi peli");
        jbtnuusi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnuusiActionPerformed(evt);
            }
        });

        jlblpelaaja.setText("Pelaajan voitot");

        jchkjaa.setText("Jää");

        jbtnnollaa.setText("Nollaa tulos");
        jbtnnollaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnollaaActionPerformed(evt);
            }
        });

        jlblkone.setText("Koneen voitot");

        jlblohje.setText("Jatka pelaamista kunnes tulos julistetaan.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlblpelaaja)
                                    .addComponent(jtxtpelaaja, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtxtkone, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlblkone)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jbtnnollaa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jlblalku))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jchkjaa)
                            .addComponent(jbtnpelaa))
                        .addGap(42, 42, 42)
                        .addComponent(jbtnuusi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jlblohje)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlblalku)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblohje)
                .addGap(18, 18, 18)
                .addComponent(jbtnpelaa)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jchkjaa)
                    .addComponent(jbtnuusi))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblpelaaja)
                    .addComponent(jlblkone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtpelaaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtkone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnnollaa)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnpelaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpelaaActionPerformed
        pelaa();
    }
        Noppa kone1 = new Noppa(6);
        Noppa kone2 = new Noppa(6);
        Noppa pelaaja1 = new Noppa(6);
        Noppa pelaaja2 = new Noppa(6);
        
        int pelaajaVoitti =0;
        int koneVoitti = 0;
        int koneSumma;
        int pelaajaSumma;
        
        private void voitot() {
        
        if (koneSumma > 21 && pelaajaSumma <=21 ) {   
            pelaajaVoitti = pelaajaVoitti+1;
            jtxtpelaaja.setText(String.valueOf(pelaajaVoitti));
            jbtnpelaa.setEnabled(false);
        }
        if (pelaajaSumma > 21 && koneSumma <=21) {
            koneVoitti = koneVoitti+1;
            jtxtkone.setText(String.valueOf(koneVoitti));
            jbtnpelaa.setEnabled(false);
        }
        if (pelaajaSumma > koneSumma && pelaajaSumma <22) {
            pelaajaVoitti = pelaajaVoitti+1;
            jtxtpelaaja.setText(String.valueOf(pelaajaVoitti));
            jbtnpelaa.setEnabled(false);
        }
        if (koneSumma >= pelaajaSumma && koneSumma <=21) {
            koneVoitti = koneVoitti+1;
            jtxtkone.setText(String.valueOf(koneVoitti));
            jbtnpelaa.setEnabled(false);
        }
        }
        private void pelaa() {
        
        if (koneSumma >= pelaajaSumma && koneSumma>=15) {
            pelaaja1.heita();
            pelaaja2.heita(); 
            
            pelaajaSumma += pelaaja1.getArvo()+ pelaaja2.getArvo();
            jtxtarea.setText("Pelaaja "+String.valueOf(pelaajaSumma + "\n"+"Kone " +koneSumma)+ " kone jäi tähän"); 
            if (koneSumma<pelaajaSumma && pelaajaSumma <=21) {
                jtxtarea.setText("Pelaaja "+ pelaajaSumma+" Voitto!" + "\n"+"Kone "+ koneSumma);
                voitot();
            } if (pelaajaSumma>21) {
                jtxtarea.setText("Pelaaja "+ pelaajaSumma+ "\n"+"Kone "+ koneSumma+ " Voitto!");
                voitot();
            }
        }
        else if (koneSumma >= pelaajaSumma && jchkjaa.isSelected()) {
            jtxtarea.setText("Pelaaja "+ pelaajaSumma+ "\n"+"Kone "+ koneSumma+ " Voitto!");
                voitot();
        }
        else if (jchkjaa.isSelected()) {
            kone1.heita();
            kone2.heita();
            koneSumma += kone1.getArvo() + kone2.getArvo();
            jtxtarea.setText("Pelaaja "+String.valueOf(pelaajaSumma + "\n"+"Kone " +koneSumma));
            if (koneSumma >= pelaajaSumma && koneSumma<=21) {
                jtxtarea.setText("Pelaaja "+ pelaajaSumma+ "\n"+"Kone "+ koneSumma+ " Voitto!" );
                voitot();
                
            } if (koneSumma>21) {
                jtxtarea.setText("Pelaaja "+ pelaajaSumma+" Voitto!" + "\n"+"Kone "+ koneSumma);
                voitot();
            }
        }
        else {
        
        pelaaja1.heita();
        pelaaja2.heita();
        kone1.heita();
        kone2.heita();
        
        pelaajaSumma += pelaaja1.getArvo()+ pelaaja2.getArvo();
        koneSumma += kone1.getArvo() + kone2.getArvo();
        jtxtarea.setText("Pelaaja "+String.valueOf(pelaajaSumma + "\n"+"Kone " +koneSumma)); 
        
        if (koneSumma > 21 && pelaajaSumma <=21 ) { 
            jtxtarea.setText("Pelaaja "+ pelaajaSumma+" Voitto!" + "\n"+"Kone "+ koneSumma);
            voitot();
        }
        else if (pelaajaSumma > 21 && koneSumma <=21) {
            jtxtarea.setText("Pelaaja "+ pelaajaSumma+ "\n"+"Kone "+ koneSumma+ " Voitto!");
            voitot();
        }
        else if((koneSumma > 21) && (pelaajaSumma > 21)) {
            jtxtarea.setText("Molemmat hävisivät.");
            voitot();
        }
        else if (koneSumma > pelaajaSumma && koneSumma >= 15) {
            jtxtarea.setText("Pelaaja "+ pelaajaSumma + "\n"+"Kone " +koneSumma+ " kone jää tähän");
            
        }
        }   
       
    }//GEN-LAST:event_jbtnpelaaActionPerformed

    private void jbtnuusiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnuusiActionPerformed
        jtxtarea.setText("");
        pelaajaSumma = 0;
        koneSumma = 0;
        jchkjaa.setSelected(false);
        jbtnpelaa.setEnabled(true);
    }//GEN-LAST:event_jbtnuusiActionPerformed

    private void jbtnnollaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnollaaActionPerformed
        jtxtarea.setText("");
        jtxtkone.setText("");
        jtxtpelaaja.setText("");
        jchkjaa.setSelected(false);
        pelaajaSumma = 0;
        koneSumma = 0;
        koneVoitti = 0;
        pelaajaVoitti = 0;
        jbtnpelaa.setEnabled(true);
    }//GEN-LAST:event_jbtnnollaaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Noppapeli3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Noppapeli3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Noppapeli3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Noppapeli3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Noppapeli3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnnollaa;
    private javax.swing.JButton jbtnpelaa;
    private javax.swing.JButton jbtnuusi;
    private javax.swing.JCheckBox jchkjaa;
    private javax.swing.JLabel jlblalku;
    private javax.swing.JLabel jlblkone;
    private javax.swing.JLabel jlblohje;
    private javax.swing.JLabel jlblpelaaja;
    private javax.swing.JTextArea jtxtarea;
    private javax.swing.JTextField jtxtkone;
    private javax.swing.JTextField jtxtpelaaja;
    // End of variables declaration//GEN-END:variables
}
